### ISSUE TITLE
Nodejs client sdk vs jsonPaymentProtocol

### ISSUE THREAD

**Issue by omariosman** [bitpay/nodejs-bitpay-client#100]
Can I ask what is the difference between nodejs-bitpay-client of this repo and [jsonPaymentProtocol ](https://github.com/bitpay/jsonPaymentProtocol)?

In other words, can I just use nodejs-bitpay-client to do all the following or I need to use jsonPaymentProtocol as well?
1. Create Invoice
2. Payment options 
3. Payment request (Select payment option)
4. Verify payment request  
5. Payment verification (send unsigned tx) 
6. Payment (send signed tx) 
7. Webhook

**Comment by bobbrodie** [comment]
Hi @omariosman I know this has been here a while and I believe you had contact with support, but I wasn't sure if you received an answer on this specifically. These can be done with the API and SDK: https://developer.bitpay.com/reference/concepts. Do let us know if we can help at all. Thanks!
