### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by anthonywebb** [bitpay/nodejs-bitpay-client#12]
In an attempt to understand if the library was working properly I downloaded fresh copy of the code.  Then I ran 
```
npm install
```
Then I ran
```
npm run test
```
This starts with Checking formatting...  But ultimately fails with
```
Code style issues found in the above file(s). Forgot to run Prettier?
```

**Comment by anbugal** [comment]
Tests in this SDK are functional so they won't work unless they contain valid keys and even then the Refund resource will fail as it requires manual action.
