### ISSUE TITLE
Bitpay integrate into existing Node.js project

### ISSUE THREAD

**Issue by shahzadthathal** [bitpay/nodejs-bitpay-client#26]
Hi,

I tried to integrate Bitpay Node.js in existing Node.js project but unfortunately no success.

Can you please let me know how to create public and private keys?
I created a merchant account at test.bitpay.com.

I downloaded https://github.com/bitpay/nodejs-bitpay-client/
and then try to run these commands:
```npm run setup``` or ```npm run .\setup\BitPaySetup.ts``` but there is error:

> npm ERR! missing script: .\setup\BitPaySetup.ts

I also created a Token here:
https://test.bitpay.com/dashboard/merchant/api-tokens

I followed this tutorial but not succeed to generate keys

https://github.com/bitpay/nodejs-bitpay-client/blob/master/GUIDE.md

I also followed this tutorial but nothing happend

https://support.bitpay.com/hc/en-us/articles/115003025486-How-do-I-configure-and-use-the-BitPay-Node-JS-Library-

What is the exact way to integrate Bitpay in our existing project, it would be realy helpful.

I'm using Windows platform.

Thanks

**Comment by shahzadthathal** [comment]
Well I fixed above issue using this method.

1. First create a test account here: https://test.bitpay.com
2. Open termnial/cmd/command line and do:  git clone https://github.com/bitpay/nodejs-bitpay-client.git
3. cd nodejs-bitpay-client/setup
4. node BitPaySetup.ts
```
node .\BitPaySetup.ts 
Select target environment:
Press T for testing or P for production:
T
Enter your private key or its location
Or press Enter to generate a brand new key:
Generating private key... 

Generated Private Key: 683f768dd9a9ccdxxxxxxxxxx
With Public Key: 0474c91c864c77f4xxxxxxxxxxx

Select the way you want to store your private key:
Press F for storing in a text file or T for plain text in your config file: F
Saving private key... 

Private key saved in file: xxxxxx\nodejs-bitpay-client-master\setup/../secure/private_key_test.key 

Select the tokens that you would like to request:
Press M for merchant, P for Payroll or B for both:
M
Requesting tokens... 

Requesting Merchant token... 

Generated configuration file
And saved in file:  xxxxxx\nodejs-bitpay-client-master\setup/../secure/BitPay.config.json

Configuration generated successfully!

To complete your setup, Go to https://test.bitpay.com/dashboard/merchant/api-tokens and pair this client with your merchant account using the pairing codes:
aE8Xzxxxxx for the Merchant facade.

```

Go to your existing project where you wnat to integrate BitPay and install:

npm install bitpay-sdk --save
 
And  then 
```
const {Client, Env, Currency, Models, Tokens} = require('bitpay-sdk');

 let client = {}
 
     tokens.merchant = '7oz6Kia8xxx'// see merchant in xxxxxx\nodejs-bitpay-client-master\setup/../secure/BitPay.config.json
    keyPlainText = '683f768dd9a' //see PrivateKey in xxxxxx\nodejs-bitpay-client-master\setup/../secure/BitPay.config.json
    client = await new Client(
        null,
        Env.Test, // Env.Prod,
        keyPlainText,
        tokens
    )

 let invoiceData = new Models.Invoice(10, Currencies.USD) 
 const result = await client.CreateInvoice(invoiceData)
 
 console.log("CreateInvoice result",result)
  ```

**Comment by anbugal** [comment]
@shahzadthathal I am glad you found the solution.
I am and closing this issue since the response was provided
