### ISSUE TITLE
Setting minimum supported node version

### ISSUE THREAD

**Issue by jekh** [bitpay/nodejs-bitpay-client#39]
Would the maintainers be amenable to declaring a minimum supported node version? Node 12 is currently the oldest non-EOL version of node, but even supporting >=8 (released in 2017) would allow typescript to target es2017, rather than es5. There are a few dependencies (underscore and bluebird, via request-promise) that could be removed by setting a higher ES target, and the emitted code would be much, much easier to step through when debugging if typescript didn't have to transpile async/await, promises, and generators.

I've been using a fork that that targets es2019 (Node 12+), removes underscore, and replaces request-promise with request-promise-native. I'd be happy to open a PR with those modest changes, and update it to whatever version of node you want, if you like.

**Comment by anbugal** [comment]
please do, take into account that it should still support node 12 as lowest maintained version

**Comment by jekh** [comment]
Thanks for merging that PR! I'll close the issue now.
