### ISSUE TITLE
Cannot find module '/var/www/html/git/bitpay/node_modules/bitpay-sdk/dist/index ---For node sdk

### ISSUE THREAD

**Issue by harsh3977** [bitpay/nodejs-bitpay-client#43]
Error: Cannot find module '/var/www/html/git/bitpay/node_modules/bitpay-sdk/dist/index'. Please verify that the package.json has a valid "main" entry

**Comment by harsh3977** [comment]
Solved by downgrading version of npm i bitpay-sdk@1.4.2102.

**Comment by jekh** [comment]
This is the issue I mentioned in this PR discussion: https://github.com/bitpay/nodejs-bitpay-client/pull/40#discussion_r774644314 The currently-published package is in a bad state because of the "src" confusion. That PR should fix it after it's merged.
