### ISSUE TITLE
With merchant token not able to use CreateRefund function in node js sdk

### ISSUE THREAD

**Issue by harsh3977** [bitpay/nodejs-bitpay-client#44]
{"error":"This endpoint does not support the `merchant` facade"} i am calling API in test with bitpay package version 1.4.2102 and the current version is not stable so am calling your API by downgrading the version.

**Comment by anbugal** [comment]
Could you provide a more detailed description of the issue? we have tested it and we can see any issues.

**Comment by harsh3977** [comment]
const result = await client.CreateRefund(
      "Jqy5r5Qhv3pJzmgY4i8TJd",
      "harshupadhyay397@gmail.com",
      1,
      "USD"
    );

While creating refund with package version 1.4.2102 it will not allow me as saying above given error.Is it show me a problem due to downgrading a version .
I am connecting client with merchant token.

here are my configuration file.
{
    "BitPayConfiguration": {
        "Environment": "Test",
        "EnvConfig": {
            "Test": {
                "PrivateKeyPath": "/var/www/html/git/bitpay/src/secure/private_key_test.key",
                "PrivateKey": "ccfc1d76de8c7daefb59318d045f1c52e750ae426259d95b37d0ee04d9e705d2",
                "ApiTokens": {
                    "merchant": "HgdaDhxECHmNdpMq44JZEn8Gh6RpiNCCEsr3Zbi2vwXB"
                   
                }
            }
        }
    }
}

**Comment by harsh3977** [comment]
Solved Applying trying same code example uploaded by yesterday.https://github.com/bitpay/nodejs-bitpay-client/blob/master/docs/usage/refunds.md.

Thanks
