### ISSUE TITLE
cannot create token, not working from init stage

### ISSUE THREAD

**Issue by jackykwandesign** [bitpay/nodejs-bitpay-client#59]
By running `node node_modules/bitpay-sdk/dist/setup/BitPaySetup.js`
i can only get a private key, no pair code, no SIN, no merchant or payout token generated

![image](https://user-images.githubusercontent.com/46065771/164885120-393a7ba7-0c7a-49c6-97b6-1ac5c943fc6d.png)
![image](https://user-images.githubusercontent.com/46065771/164885129-d4e58393-ccf7-44ff-a8fd-6a1c97cc45ee.png)

And in the dashboard, i cannot found my SIN or clientId
And there should be someway to direct generate this info in the dashboard, like generating the API token

**Comment by jackykwandesign** [comment]
Right now, i just use Bitauth to generate SIN
i get public key, private key, sin from result

And i use API `test.bitpay.com/tokens` with SIN to get merchant token and approve in the dashboard
![image](https://user-images.githubusercontent.com/46065771/164887793-d69e892c-58ed-4614-8ea5-edc8a4b6705a.png)
![image](https://user-images.githubusercontent.com/46065771/164887797-25273619-c82d-4154-8a89-cd2d0dd7564f.png)

And i can direct access API `/tokens/:token/sins`, which prove it works in API level
Before i send API, i signed ecdsa with this website
https://kjur.github.io/jsrsasign/sample/sample-ecdsa.html
![image](https://user-images.githubusercontent.com/46065771/164887919-35d63a55-9869-4049-a108-0aa54fad3233.png)

![image](https://user-images.githubusercontent.com/46065771/164887811-82e380cf-da98-4558-96cf-d25498b77bbd.png)

But then i try Bitpay-sdk again, it still give me UnhandledPromiseRejection, which i already handle trycatch in my code block,
so there is something broken in sdk
![image](https://user-images.githubusercontent.com/46065771/164887837-c5e19b35-4656-4d3b-a9a3-461a0eb473fc.png)
![image](https://user-images.githubusercontent.com/46065771/164887843-ed0d848e-161c-4a61-ae2b-c2636eec3213.png)

**Comment by jackykwandesign** [comment]
Finally, i do this from the beginning

1. Gen SIN + key pair
2. Get Token
3. Approve Token
4. Use token in code API call
5. Sign the API manually (for anyone confuse with signature, this is how to make it in Nodejs, and the result signature is same as i generate from last website, which that website is a demo of this lib `jsrsasign`, check script tag in HTML can see the whole demo )
```ts
import * as rs from "jsrsasign"
const testAPI = async () => {
	try {
		let baseURL = "https://test.bitpay.com"
		let finalURL = `${baseURL}/tokens/${process.env.BITPAY_MERCHANT_TOKEN}/sins`
		console.log("finalURL", finalURL)

		const sig = new rs.KJUR.crypto.Signature({ alg: "SHA256withECDSA" })
		sig.init({ d: process.env.BITPAY_PRIVATE_KEY, curve: "secp256k1" })
		sig.updateString(finalURL)
		var sigValueHex = sig.sign()
		console.log("sigValueHex", sigValueHex)
		console.log(
			"process.env.BITPAY_PUBLIC_KEY",
			process.env.BITPAY_PUBLIC_KEY,
		)
		const result = await axios.get(finalURL, {
			headers: {
				"Content-Type": "application/json",
				"X-Accept-Version": "2.0.0",
				"X-Identity": process.env.BITPAY_PUBLIC_KEY,
				"X-Signature": sigValueHex,
			},
		})
		console.log("result", result.data)
	} catch (error) {
		console.log("error", error)
	}
}
```

And the code suppose to be work

However, it still not working and return a cloudflare page in response
![image](https://user-images.githubusercontent.com/46065771/164890686-d3ee1128-b73f-456d-98e3-9a9a0e1b5b2b.png)
![image](https://user-images.githubusercontent.com/46065771/164890695-3ff9a9c4-ef0d-433a-a31f-fc061e97ec13.png)

And i realise the problem is my remote machine IP is dirty in Cloudflare record due to some loading test sign project
I start a new VM win10 and use postman to send same API request, and result different from local machine

Local postman:
![image](https://user-images.githubusercontent.com/46065771/164890744-3b25c51d-bf36-48c0-a111-33bf9917e836.png)

VM postman with dirty IP
![image](https://user-images.githubusercontent.com/46065771/164890755-fdb9252c-5196-41a2-beea-c543b1d9dda1.png)

So i just open a instance in AWS and all work, including this Nodejs-SDK
So maybe it will be better if SDK client can show some error message about 403, instead of unhandled reject promise

Case close ,thanks

**Comment by kameshdhana** [comment]
Leave out a breakpoint for console.log() of merchantPairCode in BitPaySetup.js & then it'll give you the pairing code.
Sadly it's not provided with the config.json

**Comment by bobbrodie** [comment]
Closing due to age, but we are actively working on and releasing SDKs so please don't hesitate to reach out if this is still something you need. Thank you!
