### ISSUE TITLE
Where is Subscription exported?

### ISSUE THREAD

**Issue by DamiToma** [bitpay/nodejs-bitpay-client#60]
There are a couple of [examples](https://github.com/bitpay/nodejs-bitpay-client/blob/master/docs/usage/subscription.md) missing the import lines, it's hard to understand how we should import those objects. For example, the Subscription object is defined in Model/Subscription/Subscription, but not exported in Models/index, so I can't find a way to import it in my scripts (and it's required to create a subscription). How can we do that?<br>

**Comment by kameshdhana** [comment]
Use yarn to install bitpay-sdk again it'll give you the methods you want to use with your setup.

**Comment by aamorozov** [comment]
@DamiToma I think `import { Subscription } from 'bitpay-sdk/dist/Model/Subscription/Subscription'` should work

**Comment by bobbrodie** [comment]
Closing due to age, but we are actively working on and releasing SDKs so please don't hesitate to reach out if this is still something you need. Thank you!
