### ISSUE TITLE
Error when calling the GetLedger client method

### ISSUE THREAD

**Issue by skpn** [bitpay/nodejs-bitpay-client#62]
Version: 3.0.2202

Description: The GetLedger client method throws an error when trying to return data from the Bitpay API.

When calling the method, the following error is thrown :
 
`error: LedgerQueryException {
  message: "failed to deserialize BitPay server response (Ledger) : Cannot read properties of undefined (reading 'data')",
  name: 'BITPAY-LEDGER-GET',
  code: 132,
  apiCode: '000000'
}`

After digging a little, it seems the Bitpay API /ledger/{currency} endpoint has a different response structure, and does not contain a 'data' property :
[ledger endpoint documentation](https://bitpay.com/api/#rest-api-resources-ledgers-retrieve-ledger-entries)

As the RESTCli get method systematically tries to read the 'data' property, this could be why the bug happens.

**Comment by kameshdhana** [comment]
Same response here
I'm not getting my ledger entries
Getting this error only
Is there any way to pass token along with it?
