### ISSUE TITLE
Running setup

### ISSUE THREAD

**Issue by anthonywebb** [bitpay/nodejs-bitpay-client#7]
I am trying to run the setup script locally from the setup folder (using node 12.14.1), but am getting an error 
```SyntaxError: Cannot use import statement outside a module```

<img width="560" alt="Screen Shot 2021-02-12 at 11 15 06 AM" src="https://user-images.githubusercontent.com/4397/107806306-e64cae00-6d23-11eb-987e-f7e2f000dbf7.png">

Is there a different way to get these public and private keys?

**Comment by anthonywebb** [comment]
Left you a pull request which resolves this https://github.com/bitpay/nodejs-bitpay-client/pull/8

**Comment by anbugal** [comment]
Thanks for your contribution @anthonywebb.

This is the easiest and fastest way to generate the keys but it uses the elliptic curve algorithm so you can generate them yourself by using the right algorithm or exporting the piece of code that does the job: 
https://github.com/bitpay/nodejs-bitpay-client/blob/master/src/util/KeyUtils.ts

**Comment by anthonywebb** [comment]
@anbugal cool, thanks!  Also in that PR is a fix for when people use caps to request (M)erchant (P)ayroll or (B)oth

I was not getting any pairing codes and could not figure out why, this fixed that

**Comment by anbugal** [comment]
merged
