### ISSUE TITLE
{ error: 'Invalid signature' }

### ISSUE THREAD

**Issue by rahul-0210** [bitpay/nodejs-bitpay-client#74]
Getting this error when creating invoice via api on test server

**Comment by bobbrodie** [comment]
Hi @rahul-0210 we are in the process of rewriting the Node.js SDK, but if you can share replication steps, including Node.js version, SDK version, and a script to replicate your issue, that would be very helpful. Thanks!

**Comment by kameshdhana** [comment]
Hey @bobbrodie ,
I have one query while using client.GetLedger(Currency.USD,startDate,endDate) with my bitpay setup
It throws some error like this

[error: LedgerQueryException { message: "failed to deserialize BitPay server response (Ledger) : Cannot read properties of undefined (reading 'data')", name: 'BITPAY-LEDGER-GET', code: 132, apiCode: '000000' }](url)

Can you guys show me some alternative method of how to get Ledger details?

**Comment by bobbrodie** [comment]
Hi @kameshdhana I believe that this is off-topic and is better suited for #62. I see you also posted there. We'll check on this. Thanks!

**Comment by kameshdhana** [comment]
@bobbrodie Thanks

**Comment by bobbrodie** [comment]
Closing due to age, but we are actively working on and releasing SDKs so please don't hesitate to reach out if this is still something you need. Thank you!
